version: "2.1"
services:
  reviews-ms:
    build: "./nodejs-microservice"
    command: npm start
    depends_on: 
     - reviews-db
    ports:
      - "3003:3003"
      
    #command: "docker run  -d --publish 4000:4000 -e MYSQL_USER='root' 
#-e MYSQL_PASSWORD='password' -e MYSQL_DATABASE='test' -e MYSQL_HOST='172.17.0.4' 
#--link test-mysql-microservice:db --name=test-nodejs-microservice test-nodejs"

  reviews-db:
    build: "./mysql-microservice"
    ports:
      - "3310:3310"
