version: "2.1"
services:
  reviews-ms:
    build:
      context: ./nodejs-microservice  
      dockerfile: Dockerfile
    depends_on: 
      reviews-db:
        condition: service_healthy
    ports:
      - "3003:3003"
    links:
      - reviews-db
      
  reviews-db:
    build: 
      context: ./mysql-microservice
      dockerfile: Dockerfile
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck --user=root -p$$MYSQL_ROOT_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: reviewPassword
      MYSQL_DATABASE: review_suggestions
      #MYSQL_USER: root
      #MYSQL_PASSWORD: reviewPassword
    ports:
      - "6603:3306"
