version: "2.1"
services:
  reviews-ms:
    build: "./nodejs-microservice"
    command: npm start
    depends_on: 
     - reviews-db
    ports:
      - "3003:3003"
      
  reviews-db:
    build: "./mysql-microservice"
    ports:
      - "3310:3310"
